### ISSUE TITLE
Invalid Function.length property caused by JSR.

### ISSUE THREAD

**Issue by martinbednar** [polcak/jsrestrictor#110]
The length property indicates the number of parameters expected by the function.

JSR changes the values of the Function.length property, which is unintentional and undesirable. Changed value of the Function.length property can serve as an indication to fingerprinting scripts that JSR is installed in the browser.

Function.length documentation: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length)

**Comment by martinbednar** [comment]
Example in Mozilla Firefox ESR (Extended Support Release) Version 78.14.0esr (64-bit) on Windows 10.

Without JSR:

`> Date.now.length`
 `< 0`

With JSR :

`> Date.now.length`
 `< 1`

Printscreen - Firefox with JSR level 3:
![JSR-length-error](https://user-images.githubusercontent.com/15677706/132456875-861d57fe-dc78-45ff-b10b-f7f29c6a38fb.png)

**Comment by martinbednar** [comment]
I can not reproduce the error every time, when I query the length property. The wrong value in the length property occurs only sometimes. So far, I haven't figured out what triggers the error yet.

**Comment by polcak** [comment]
It seems to me that JShelter still suffers from the bug in 0.10 while Chromium-based versions do not.

**Comment by polcak** [comment]
I moved the issue to https://pagure.io/JShelter/webextension/issue/65
