### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by WeeBaldie** [polcak/jsrestrictor#112]
JSR installed without problem, yet when I clicked on the button, only a narrow, vertical strip of the box is displayed. See .png image attached.

![Clipboard02](https://user-images.githubusercontent.com/14280056/135707338-f54d584f-1898-428d-8c64-a0396de88063.png)

**Comment by mirql** [comment]
same

**Comment by tortino** [comment]
happens to me too

**Comment by mechanyx** [comment]
I have this problem in Brave 1.30.87 and Chromium 1:85.0.4183.83-0ubuntu2 (this is a snap) on Ubuntu Gnome on a 4K display. It should be noted that some other extension drop downs display poorly with this combination but this one is significantly worse as I'm unable to use the drop down at all.

I have no problems with Firefox 92.0+build3-0ubuntu0.21.04.1 on the same system.

**Comment by nPHYN1T3** [comment]
Yup went to try this and all I get is that vertical sliver of UI you can't read, use or interact with. Brave here as well though Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit) is a bit of a trash heap.

**Comment by alphamichael** [comment]
Same on `Windows 10` `Chrome Version 94.0.4606.71 (Official Build) (64-bit)`

**Comment by TechnologyClassroom** [comment]
@WeeBaldie @mirql @tortino  Can you provide more details?  What is your browser, browser version number, operating system, and operating system version number?

**Comment by darkred** [comment]
To contribute, here are mine: Chrome 94, Win10 x64.

**Comment by WeeBaldie** [comment]
Chrome 94.0.4606.71, Win 10 21H1 19043.1237

Cheers.

**Comment by polcak** [comment]
As far as we are aware this bug affects Chromium when used with a big screen. We might have a short-term fix that we want to deploy before we release redesigned UI, see https://lists.nongnu.org/archive/html/js-shield/2021-10/msg00004.html.

As a workaround, do not use the pop up for the settings but use the main settings page. It is not as comfortable as using the pop up but all configuration is also available through the settings page.

**Comment by nPHYN1T3** [comment]
Ye Olde query total screen size rather than window size for scaling ;p
