### ISSUE TITLE
Add support for Firefox Mobile

### ISSUE THREAD

**Issue by json1c** [polcak/jsrestrictor#113]
Please, add support for FF Mobile

**Comment by polcak** [comment]
We are investigating this option. If anyone wants to volunteer for the testing, please, contact me.

**Comment by json1c** [comment]
Im wants to be him

**Comment by polcak** [comment]
We checked that current implementation should work but there are no automated tests. Please send me an e-mail if you want to be notified about new versions or even help with automated tests.

We should release 0.5.1 soon and it will be marked as compatible with Firefox for Android.
