### ISSUE TITLE
Shield Enabled For This Site Always Says Yes

### ISSUE THREAD

**Issue by mechanyx** [polcak/jsrestrictor#114]
Using Firefox 92.0+build3-0ubuntu0.21.04.1 on Ubuntu Gnome, whenever I open the drop down for the extension, at the bottom is a section that says "Network boundary shield" and then "Shield enabled for this site:" with a yes/no position slider. The slider is always set to "YES". If I slide it to "NO", a refresh page option comes up. Regardless of whether I choose that or not, the next time I open drop down, the slider is in the "YES" position. It is unclear to me whether this is merely a UI issue and it shows "YES" even if it is disabled or if the slider is failing to turn the shield off when set to "NO".

I'm unable to test this in Chromium or Brave as I'm impacted by the UI issue detailed in #112 in those browsers.

**Comment by polcak** [comment]
Confirmed. This seems to be a UI issue as the settings is visible in the main settings page.

**Comment by polcak** [comment]
Yes it was just the UI issue.
