### ISSUE TITLE
Black icon is hard/imposible to see in dark theme.

### ISSUE THREAD

**Issue by bjwest** [polcak/jsrestrictor#115]
The black icon can barely be seen with a dark theme in use.  Is there any way to detect the theme and use a lighter icon or, if not, make a settings option?

**Comment by TechnologyClassroom** [comment]
Using the hermit crab logo for the icon would solve this issue: https://jshelter.org/theme/images/jshelter-hero.svg

**Comment by polcak** [comment]
As we are in the phase of rebranding, the icon will be replaced by the crab. As it will make life for some users easier, we will replace the icon ASAP.
