### ISSUE TITLE
Feature request: additional browser

### ISSUE THREAD

**Issue by slackuser0xae34** [polcak/jsrestrictor#117]
Please add support for FSF IceCat (60.7.0esr). Thanks.

**Comment by polcak** [comment]
See https://www.gnu.org/software/gnuzilla/addons.html for more details on IceCat extensions. I asked for adding to the list, see https://lists.nongnu.org/archive/html/js-shield/2021-10/msg00005.html. Is there another issue?

**Comment by slackuser0xae34** [comment]
I couldn't find the add on at the GNU extensions web site, yet. 

However, I downloaded the 'xpi' add-on file from the Mozilla add on site, using IceCat 60.7.0esr (the latest). I received a warning from Mozilla, on the web page, stating: "You need an updated version of Firefox for this extension".

Never the less, I tried to install it through the IceCat "Tools" -> "Add-ons" -> 'Cog' -> 'Install Add-on from File". I received a message stating that the add-on was incompatible with Ice Cat.

<aside>
FTR, IceCat doesn't appear to be compatible with GitHub either. Similarly PaleMoon (29.1.1, 32 bit) is also not compatible with GitHub. Perhaps JS Restrictor / JShelter may have issues with this version of PaleMoon.
OS: Linux, Slackware 14.2
</aside>

**Comment by polcak** [comment]
Ah sorry, my bad, I missed the version number. We support 68.0 and above. AFAIK PaleMoon does not support webextensions so we do not support PaleMoon.

**Comment by polcak** [comment]
Is IceCat 60.7.0 still the latest? I received information from FSF that a newer version should be released months ago.

If you are interested in trying in IceCat 60.7.0 you will likely need 9a47f7517c9af5b6eb4bb9ceea8ade949eccc2a9 and building the extension by yourself. Please, let me know if you were able to use the extension in the latest IceCat.

**Comment by slackuser0xae34** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

2022/02/03

Polcak,

I believe that there is a newer version of IceCat than 60.7.0. However,
the FSF has gone to (another) new package manager application. I'm
package manager'ed out. The newer version is available as source, but
the dependency tree is extensive. Too many dependencies which are not
normally included in my distro (Slackware-14.2 * 15.0 (just released)).

I'm still using IceCat 60.7.0, even with the risks, but carefully on
known reputable sites. Otherwise, I'm using PaleMoon and I have
reluctantly started using Firefox again. (After neutering FF telemetry
with the known anti-telemetry hacks as well as by setting
mozilla.com/net/org to 127.0.0.1 in my hosts file).

I'm hoping (probably futilely) that the later IceCat will be properly
released as a binary, or perhaps through a Slackbuild.

I will take a look and try to build the referenced version in the near
future. When I have anything to report, I'll let you know.

Many thanks for your interest and reply. Good luck and Happy New Year.

Best Regards

Ric F.

###############################################
On Thu, 03 Feb 2022 07:46:16 -0800
polcak ***@***.***> wrote:

> Is IceCat 60.7.0 still the latest? I received information from FSF
> that a newer version should be released months ago.
> 
> If you are interested in trying in IceCat 60.7.0 you will likely need
> 9a47f7517c9af5b6eb4bb9ceea8ade949eccc2a9 and building the extension
> by yourself. Please, let me know if you were able to use the
> extension in the latest IceCat.
> 
> 
> 



- -- 
Five basic forces of the universe, in order of power:
stupidity, electromagnetic, gravity, strong atomic, weak atomic.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJh/FnEAAoJEMhtenyuSrhDJV0P/jNko1t3pMjSZ3bgX6Sv5YjT
3AnKTPoNDJoYmqsQ373uUmKJvKJP3bm1ZYgc5DMUYZW3oBSRouNgcqEyALlFKURe
chcz9s4o97KXJa5c0lbxFRx8zVIINjdI9AS1sM7Jsv3p26cdXsziC88hm391vY6T
D4/Hady7aoHu/Yvx/o0946CFfB4i/hs2cclCSpHs33kf5VFZwNRexGmMKhOEtRGm
c1fChy/QMX5cTgAQQ4p2/b6Iu/hxbOtvyMEwNv9rECNROAn1rcgQJprJb5bTRyKi
KgebwPi8KjAvWoccRZbx/6XUc91svqWEILOCweAiRTq92F1aEJLbAXYUPf31+gcH
15EFBRehf4zhnbHL1Z5BKI7YPjq7I3NJmcxIGy6ivszbpdQ8VGNaB21butBOgAYM
DdNQniDjbYerhdikjv5pVtfIV3ogRYCSsqi8hImkvMN3e58qt0c1ty6wx4AvgEpN
Ivc99Qci+BsTt8qJp/pBKW9VMNza4x3yVlebBCMamUM0fVdXGALJNfAbX7eQdx0v
cgd6k3/SX7e1DFHgZ4xqiJasCrQspHY0iKCTVNYJ1BuuXGsQBnY4Osn8uOpGRLBs
0eNmFo1gZZuBkA+LRef8/8fqBq1rrjE1PJyfWZUBumjJ0OeEKvR+9jcLLJjU+EbR
KAWsMqCV63YX+dfa6tQ/
=YL2f
-----END PGP SIGNATURE-----

**Comment by TechnologyClassroom** [comment]
Developing a slackbuild for IceCat or IceCat itself is out of scope for the JShelter project.

I am not an IceCat dev, but I regularly talk with one of them.  There are a few blockers remaining with a new official IceCat release.  IceCat is developed by volunteers so the next binary will release when it is released.  If you want to try on the new release, you will have to compile from source.  On Slackware, you would have to compile the dependencies too.  The only distribution that I know of that has a new version of IceCat is Guix.  It is possible to use the Guix build system on other operating systems, but I am not sure about Slackware and I do not use Guix myself.  You could follow the steps to [build the dependencies of Firefox ESR from Linux From Scratch documentation](https://linuxfromscratch.org/blfs/view/svn/xsoft/firefox.html) which should allow you to then build the latest IceCat.  I do not use Slackware, but maybe the work that Guix or LFS did can be used to make slackbuilds.

**Comment by polcak** [comment]
> After neutering FF telemetrywith the known anti-telemetry hacks as well as by setting mozilla.com/net/org to 127.0.0.1 in my hosts file).

@slackuser0xae34 Use 0.0.0.0 instead of 127.0.0.1 to prevent Firefox from talking to your local applications.

@TechnologyClassroom: Do we want to support IceCat 60? For 0.4 the only needed fix was 9a47f75 but since then we have a lot of new code which might be fine but there might be additional incompatibilities.

**Comment by TechnologyClassroom** [comment]
@polcak No, Firefox 60.x is [end-of-life](https://wiki.mozilla.org/Release_Management/Calendar).  Any privacy or security benefits that JShelter would provide would be negated by using such an out-of-date program.  I successfully tested JShelter with IceCat 78+.
