### ISSUE TITLE
what about official (Matrix?) chatroom?

### ISSUE THREAD

**Issue by okias** [polcak/jsrestrictor#121]
Would be nice to have some place where users can ask simple questions and chat about JS, privacy and all the stuff around this project.

If there is already one covering these topic, would be great to point to it.

**Comment by polcak** [comment]
Feel free to create an unofficial one. If you are interested, there is a mailing list for the project, see https://lists.nongnu.org/mailman/listinfo/js-shield.

**Comment by TechnologyClassroom** [comment]
@okias #jshelter is now on Libera.Chat IRC.  I hear every Libera.Chat room has a matrix bridge as well.
