### ISSUE TITLE
Content from icon is not visible

### ISSUE THREAD

**Issue by sterndata** [polcak/jsrestrictor#126]
The width here is messed up.  [Screenshot](https://i.imgur.com/BEeZ7En.png)

**Comment by TechnologyClassroom** [comment]
Can you provide some more details?  What is your browser and your browser's version?

**Comment by TechnologyClassroom** [comment]
Duplicate of https://github.com/polcak/jsrestrictor/issues/112

**Comment by sterndata** [comment]
Chrome / Fedora 34
Version 94.0.4606.71 (Official Build) (64-bit)
