### ISSUE TITLE
Enable more fine grained control on a per. site control

### ISSUE THREAD

**Issue by TanyaMaiRandstoft** [polcak/jsrestrictor#131]
Using the plugin disables functionality I need for work on some applications. Among those are GChat and MS-Teams - It would be good if it was possible to enable functionality back on a "by site" and "by feature" matrix, so I can still have the plugin enabled for "everything else" but allow a few "bad apples" to run that are required by work.

**Comment by polcak** [comment]
Hello,

we plan this functionality for the next major release. Feel free to read https://lists.nongnu.org/archive/html/js-shield/2021-08/msg00003.html. Comments welcomed.

**Comment by polcak** [comment]
This feature will land in 0.7, see https://pagure.io/JShelter/webextension/tree/devel0.7.
