### ISSUE TITLE
sendbeacon should be treated the same as xhr

### ISSUE THREAD

**Issue by GrosSacASac** [polcak/jsrestrictor#132]
sendbeacon can do less things than xhr, (it can only send)

also it is miss-labeled as analytics, it can be used for that but also for sending other things like shopping bag sync when the tab is closed or session closing

**Comment by polcak** [comment]
Thanks for pointing out. If you want to discuss further, please send message to the mailing list, see https://lists.nongnu.org/archive/html/js-shield/2021-10/msg00012.html.

**Comment by polcak** [comment]
Fixed in 0.7
