### ISSUE TITLE
BUG: Google Recaptcha not working

### ISSUE THREAD

**Issue by stemberajan** [polcak/jsrestrictor#138]
If I go to the web, where is Recaptcha test, it it only rotating wheel and nothing more. If I uninstall jsrestrictor Recaptcha is working.
I tried to set Level form 2 to 0 and no success.

It does on Firefox Esr and on Srware Iron/Chrome too.

**Comment by polcak** [comment]
This seems like a duplicate of #133 and should be fixed in 0.5.3. Feel free to reopen/comment if this is not fixed by 0.5.3.

**Comment by stemberajan** [comment]
Recaptcha - jsrestrictor version 0.5.4 was working, but 0.5.5 is not working again.

**Comment by stemberajan** [comment]
@polcak
