### ISSUE TITLE
compatibility with RFP, FPI

### ISSUE THREAD

**Issue by atomGit** [polcak/jsrestrictor#140]
how well does JSR play with `privacy.resistFingerprinting` because JSR seems to overlap with RFP, such as with canvas, location, etc.

**Comment by polcak** [comment]
Well, this is a good research question which can be divided into more subquestions like does `privacy.resistFingerprinting` work well? If the goal is to prevent fingerprinting, is the idea of pretending that everyone has the same configuration a sound one? Should we rather create a different fingerprint for each domain and session (see https://polcak.github.io/jsrestrictor/blogarticles/farbling.html for more details). Should we let the page perform the fingerprinting but block it from uploading the fingerprint?

This is an experimental extension and we do not have definite answers to the questions. I am not sure if there ever will be definite answers as they may depend on your security model.

What are you trying to achieve with `privacy.resistFingerprinting` and what is your goal why you want to use JSR?

**Comment by atomGit** [comment]
> is the idea of pretending that everyone has the same configuration a sound one?

i think it is as long as enough browser instances (users) return the same data - whether randomizing the data is a better method, i can't say for sure due to a lack of technical knowledge, however it seems that you would propose that "Farbling" is better than the former - is that what JSR is doing (at least in part)?

> What are you trying to achieve with privacy.resistFingerprinting ...

resist fingerprinting, of course, as in preventing a site from identifying the browser uniquely 

> ... and what is your goal why you want to use JSR?

to restrict what JS can access/do - finer-grained control than what uBO offers

regarding my original question however, it remains unanswered; does JSR interfere with RFP given that there seems to be overlap? i ask because, far as i know, messing with RFP stuff can lead to greater entropy

my million $ question: given the current state of JSR, what is your recommendation; do you think it would be better to use only JSR , or use both JSR and RFP?

also what, if any, relevant JS APIs are left unprotected by JSR at this time?

and, if you feel like answering, have you conversed with the FF devs regarding RFP and how it's implemented? it seems like your approach with JSR might be preferable

**Comment by PhysicsIsAwesome** [comment]
@atomGit: these are very good question. I also hope to get an answer 😉

**Comment by polcak** [comment]
Please, see blog posts https://jshelter.org/blog/ and the docs under the KEY PROTECTION heading on the JShelter.org. Specifically, we recently added FPD https://jshelter.org/fpdetection/. For now, opt-in is required.

> i think it is as long as enough browser instances (users) return the same data - whether randomizing the data is a better method, i can't say for sure due to a lack of technical knowledge, however it seems that you would propose that "Farbling" is better than the former - is that what JSR is doing (at least in part)?

1. If you want to have same fingerprint as a lot of users, I suggest going for Torbrowser (without JSR).
2. If you want to make cross-site linkage hard, go for level 2. If you want better protection for the real data at the cost of having the same fingerprint on different sites, go for level 3.
3. If you want to detect and prevent fingerprinting attempts, turn FPD on (JSR 0.6+ required).

> resist fingerprinting, of course, as in preventing a site from identifying the browser uniquely

The site knows your IP address, are you sure that the address is shared with enough people with the same fingerprint?

> regarding my original question however, it remains unanswered; does JSR interfere with RFP given that there seems to be overlap? i ask because, far as i know, messing with RFP stuff can lead to greater entropy

Yes, there is an overlap. Your identity set will likely be like All Firefox users having RFP AND JSR users AND having the same IP address AND having the same screen size AND having the same OS ...

> my million $ question: given the current state of JSR, what is your recommendation; do you think it would be better to use only JSR , or use both JSR and RFP?

I would recommend RFP and JSR level 2 with active FPD. Please report the issues that you might encounter. I think that RFP is useful for APIs like fonts. The browser is much better position for this task then an extension. Also RFP protections are applied by Torbrowser so they are tested on much broader audience.

> also what, if any, relevant JS APIs are left unprotected by JSR at this time?

The page would have access to the real values. This is also a reason why I think that it might be a good idea to turn RFP on.

> and, if you feel like answering, have you conversed with the FF devs regarding RFP and how it's implemented? it seems like your approach with JSR might be preferable

No I did not discussed with FF devs but I know https://2019.www.torproject.org/projects/torbrowser/design/#fingerprinting, https://wiki.mozilla.org/Security/Fingerprinting, https://bugzilla.mozilla.org/show_bug.cgi?id=1329996, https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting.

RFP may be useful for cases like having a common laptop with default settings that changes IP addresses a lot. But if you like to have the same FP as a lot of other users, go for the Torbrowser.

Also, the issue with RFP is that you need to accept the preselected behaviour - font and screen size, timezone, disabled APIs. JSR tries to give you an option to have sites working as well as possible and intended while limiting access to some APIs and detecting and blocking FP attempts.

The reason we develop JSR/JShelter is that we think that 2.+3. is better. But as I said above, this is still an interesting open research question.

**Comment by polcak** [comment]
RFP creates white noise images from canvas data (https://pagure.io/JShelter/webextension/issue/25), there is no point to farble such an image. With RFP on, I also do not recommend activating the Strict Canvas protection. I will try to reorganize wrapping groups for 0.8 so that it is possible to turn off all canvas reading protection with one slider without affecting other WEBGL protections, see https://pagure.io/JShelter/webextension/issue/27.

We should detect RFP and modify behaviour accordingly, see https://pagure.io/JShelter/webextension/issue/34

**Comment by polcak** [comment]
I added notes on RFP to FAQ (soon to be published). We have other issues opened like https://pagure.io/JShelter/webextension/issue/34. I am closing the issue. If there are any additional questions, feel free to raise them.
