### ISSUE TITLE
Cannot remove protection for specific domains

### ISSUE THREAD

**Issue by mudnug** [polcak/jsrestrictor#147]
Load Version 0.5.2 into a Brave browser (or something Chromium based).
Open Options and go to options_domains.html
Enter any domain into "Set level of protection for website:"
Click add to list

Expected: Item is saved.
Actual: nothing is saved. Console error is logged
Uncaught ReferenceError: browser is not defined
    at saveDomainLevels (levels.js:786)
    at HTMLButtonElement.<anonymous> (options_domains.js:148)

**Comment by polcak** [comment]
This is a known bug that will be fixed in 0.5.3.
