### ISSUE TITLE
Roundcube not loading emails

### ISSUE THREAD

**Issue by brabitom** [polcak/jsrestrictor#150]
With active add-on (tested on Firefox and Chrome), the list of emails in Roundcube is empty.
I can see the folders, but not the emails.

![roundube](https://user-images.githubusercontent.com/936754/138886520-0f54368b-de1b-43a4-88ac-e6e3b010df7d.png)
.

**Comment by fiddleypotato** [comment]
Same here, and lucky me to find this while looking for other stuff, otherwise I would never have found the reason.

**Comment by polcak** [comment]
I tried roundcube at https://roundcube.fit.vutbr.cz, Recommended level, Firefox, JShelter 0.9. Everything works fine for me. Is the issue still valid? If so, can you, please, provide more details? Like Roundcube version, URL.

1. Navigate to a page that you are having trouble with: [URL]
2. Click on the JShelter badge icon.
3. Is JavaScript Shield active? [ON/OFF]
3. Is Network Boundary Shield active? [ON/OFF]
3. Is Fingerprint Detector active? [ON/OFF]
4. What fingerprint likelihood does Fingerprint Detector report?
5. Did Fingerprint Detector produce any notifications, if so, what was the notification?
6. Click on the `Modify` button next to the JavaScript Shield label.
7. What is the highlighted level button text?
8. Click on the `Detail tweaks of JS shield for this site` button.
9. What wrappers were triggered by the page, list them below:

Try to tweak the wrappers, use different JavaScript Shield levels. Have a look at the Web Dev Tools. Are there any errors in the console? I do not see any error related to JShelter in my setup.

**Comment by polcak** [comment]
I am closing for the lack of activity.
