### ISSUE TITLE
Firefox repeatedly warning about jsrestrictor “slowing down computer”

### ISSUE THREAD

**Issue by p3k** [polcak/jsrestrictor#151]
Using the Firefox add-on for a few weeks now with only minor configuration changes I noticed some tabs are restoring endlessly and the browser displays a warning together with the suggestion to stop the add-on.

If I do so, the tabs load normally again. Could be a side-effect with another add-on, I am using quite a bunch. Still, the browser complains about _this_ add-on, so here I go.

**Comment by polcak** [comment]
This is possibly (but not necessary) related to #144.

**Comment by Brikkbaby87** [comment]
Up

**Comment by polcak** [comment]
Until we have more data, we cannot do anything with the issue.

**Comment by polcak** [comment]
There are pages that are slowed down by JShelter, they even render the page compeltely unresponsive, see https://pagure.io/JShelter/webextension/issue/16.

I am closing this issue as there is not any progress.

**Comment by polcak** [comment]
For a future reference, it is a good idea to combine JShelter with tracker blocker extension like uBlock Origin.
