### ISSUE TITLE
recaptcha and Google Play webpage not working properly

### ISSUE THREAD

**Issue by fiddleypotato** [polcak/jsrestrictor#156]
Any kind of verification that uses recaptcha will fail (I first encountered this on the coinmarketcap website), and the Google Play website won't work properly, unable to create or edit reviews or install applications, as the dialog to select the device to install won't show up.

**Comment by zane-sano** [comment]
Before this worked on level 1. Now you have to disable the protection and then enable it again. But the moment you do that you become unidentifiable. To solve it you can create a custom level and enable everything, except `Filter XMLHttpRequest requests` and `Prevent websites from learning information on local Virtual Reality displays`.

**Comment by zane-sano** [comment]
Before this worked on level 1. Now you have to disable the protection and then enable it again. But the moment you do that you become unidentifiable. To solve it you can create a custom level and enable everything, except ~`Filter XMLHttpRequest requests`~ (you need it but you can set "ask before") and `Clear window.name value on the webpage loading`.

**Comment by bertvandepoel** [comment]
Yeah, I've been wondering, is reCaptcha now just completely incompatible with this tool? It keeps loading forever if I don't turn off protections, it seems.

**Comment by polcak** [comment]
@bertvandepoel: Some users reported that it is enough to disable window.name wrapper. Others reported that you need to set L1 and disable window.name wrapper. It seems the recaptcha behaves differently on some sites. See also https://pagure.io/jShelter/jShelter/issue/5.

We will investigate broken pages during our evaluation phase of the NLNet project. If you want to help you can provide information like if there is any output to the console (see webdev tools in your browser), what (custom) levels work.

**Comment by polcak** [comment]
I checked that Google ReCaptcha works if `window.name` wrapper is disabled (configurable as Persistent identifier of the browser tab).

`window.name` wrapper is disabled by default in latest versions for Firefox because all supported versions of Firefox offer good enough protection. We are working on mimicing the protection for Chromium-based browsers, see https://pagure.io/JShelter/webextension/issue/46.

I will close the issue but if you feel that there are additional steps that needs to be done, please let us know.

**Comment by edmcman** [comment]
FWIW, I immediately uninstalled the extension after this failed in Chrome.  I would suggest verifying that JS restrictor works out of the box on such ubiquitous sites if you want to attract users.

**Comment by polcak** [comment]
0.11 also fixes this in Chromium-based browsers
