### ISSUE TITLE
browser not accepting input where input should be accepted during Stripe payment

### ISSUE THREAD

**Issue by nobodyatandnothing** [polcak/jsrestrictor#157]
Steps to reproduce the problem:
1.go to https://www.redbubble.com/
2.add item to cart
3.go to cart
4.click "pay by credit card"
5.enter shipping details
6.click continue

What is the expected behavior?
Credit Card Number input area accepts typed numbers

What went wrong?
cannot select or type in Credit Card Number input area

Chrome version: 96.0.4664.45  Channel: stable

**Comment by polcak** [comment]
I cannot reproduce without giving my data? Is this still valid? Do you see any errors in developer tools console?

It would help if you provide additional data:

1. Click on the JShelter badge icon.
3. Is JavaScript Shield active? [ON/OFF]
3. Is Network Boundary Shield active? [ON/OFF]
3. Is Fingerprint Detector active? [ON/OFF]
4. What fingerprint likelihood does Fingerprint Detector report?
5. Did Fingerprint Detector produce any notifications, if so, what was the notification?
6. Click on the `Modify` button next to the JavaScript Shield label.
7. What is the highlighted level button text?
8. Click on the `Detail tweaks of JS shield for this site` button.
9. What wrappers were triggered by the page, list them below:

**Comment by nobodyatandnothing** [comment]
i no longer use jsrestrictor
