### ISSUE TITLE
Payment via Stripe requires to turn off wrapers

### ISSUE THREAD

**Issue by tfardet** [polcak/jsrestrictor#160]
It seems that, at least for some pages, payment via [Stripe](https://stripe.com/) does not work if JSrestrictor is enabled.
Neither level 1 nor 2 worked and I had to turn the wrappers off to make the payment.

**Comment by polcak** [comment]
Please provide steps to reproduce. What URL should I visit, what steps should I make, what are the expected results of these steps, and what are the actual results?

**Comment by polcak** [comment]
Duplicate of #157
