### ISSUE TITLE
jsrestrictor 0.5.5 can cause sigsegv in vivaldi for some sites

### ISSUE THREAD

**Issue by stercomm4** [polcak/jsrestrictor#162]
![Screenshot from 2021-12-31 12-18-00](https://user-images.githubusercontent.com/13934800/147836836-fe7a2896-3fed-4213-8058-e84cb14b4fa1.png)

**Comment by stercomm4** [comment]
when jsrestrictor is disabled, sigsegv does not occur

**Comment by polcak** [comment]
Hello,

we are not in possition to allocate memory. This seems like a bug in Vivaldi. Please file bug with Vivaldi and report the result and the link to the bug.
