### ISSUE TITLE
Cover getComputedTextLength API

### ISSUE THREAD

**Issue by KOLANICH** [polcak/jsrestrictor#163]
https://apireference.aspose.com/html/net/aspose.html.dom.svg/svgtextcontentelement/methods/getcomputedtextlength

**Comment by polcak** [comment]
I guess that returned length could be farbled. But it seems that strange inconsistencies can arise that could affect benign pages.

**Comment by polcak** [comment]
See https://pagure.io/JShelter/webextension/issue/60. I am closing this, if you have additional comments, you can provide them here or preferably on Pagure.
