### ISSUE TITLE
ReCaptcha broken on all pages

### ISSUE THREAD

**Issue by DOFfactory** [polcak/jsrestrictor#168]
Please provide a fix for reCaptcha, as it does not work in any of the pages. Not even if I add an exception, lower the protection to minimal. Only turning off the extension helps.

**Comment by bircoph** [comment]
Just for the record: recaptcha works for me on the minimal level on most pages, but I have to disable jsrestrictor completely occasionally.

**Comment by polcak** [comment]
AFAIK duplicate of #156. Feel free to say if this is about a different service.
