### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Rexadev** [polcak/jsrestrictor#170]

**Comment by TechnologyClassroom** [comment]
The default reddit is slow on my computer with or without JShelter.  I would recommend https://old.reddit.com for a lighter version.

What is your JShelter version, browser, browser version, operating system, and operating system version?

**Comment by Rexadev** [comment]
> What is your JShelter version, browser, browser version, operating system, and operating system version?

JShelter version - 0.6.5
Browser - Chromium  98.0.4758.80
operating system version - Windows 10 21H1

**Comment by polcak** [comment]
We can locate specific wrappers in the tweaks UI of 0.7 popup
