### ISSUE TITLE
Fingerprinting detection improvements

### ISSUE THREAD

**Issue by jrabinow** [polcak/jsrestrictor#172]
The fingerprinting detection could stand to be improved. For example, going to https://maphub.net/hyperknot/custom-markers-berlin-zoo (or any other map on maphub) blocks loading map tiles unless "fingerprinting detection" is turned off.

As there are a large amount of websites, each with their own custom case to deal with, I'd expect this kind of problem comes up relatively often. Is there a way to make reporting these kinds of issues easy, or a plan around adding support for something in the same vein as adblock lists? Or maybe there is some other plan that would help distribute the burden of fixing every website amongst the community?

Many thanks for building and supporting this extension!

**Comment by polcak** [comment]
There are two issues so I created:

* https://pagure.io/JShelter/webextension/issue/19
* https://pagure.io/JShelter/webextension/issue/20

If you are willing to help, feel free to sign up to the mailing list https://lists.nongnu.org/archive/html/js-shield/

**Comment by polcak** [comment]
@jrabinow: Mapub seems to work for me with JShelter 0.16. Can you have a look and confirm that the issue is actually fixed? If not, can you use the new issue template for a broken page and provide more details? Thanks.

**Comment by jrabinow** [comment]
I don't remember really well what the broken page looked like, it's been a moment 🙂 that being said, mapub now does seem to work without anything broken. Thank you!
