### ISSUE TITLE
[Question] Did latest version changed default to Minimal and renamed it to Recommended?

### ISSUE THREAD

**Issue by Rexadev** [polcak/jsrestrictor#175]
In the latest version 2022-02-25 there are 4 levels - 

0 Off (was off)
1 Recommended (was minimal)
2 Strict (was recommended)
3 Experimental (was strict)

Most sites worked for me on level 2 (previous version naming)

**Comment by polcak** [comment]
The changelog should be visible at https://jshelter.org/versions/ but sill is not, sorry for that. See https://github.com/polcak/jsrestrictor/blob/master/website/content/pages/versions.md, specifically:

* Level 1 removed as it was not properly maintained.
* XHR wrappings and (sharred) array buffers not wrapped anymore as XHR is superseded by FPD and array buffers break other APIs.
* New experimental level added that is based on original level 3.
* Better and much longer description of built-in levels.

So to correct:
0 Off (was off)
1 Recommended (was Recommended)
2 Strict (was Strict but features that do not work well removed)
3 Experimental (technically was strict, currently based on strict and all protections set to maximal, there are no promises on keeping this level, having this level based on Strict, however, if I do change/delete the level, I'll probably automatically create a user-defined level with the previous behaviour for those that are using the level. Do not use the level.)

(See https://github.com/polcak/jsrestrictor/blob/0.6.5/common/levels.js#L666 for 0.6.5 levels and https://github.com/polcak/jsrestrictor/blob/0.7/common/levels.js#L625 for 0.7 levels. See also https://lists.nongnu.org/archive/html/js-shield/2022-02/msg00004.html.)
