### ISSUE TITLE
Gigabyte's website is broken

### ISSUE THREAD

**Issue by moshiur-raj** [polcak/jsrestrictor#191]
Whenever I visit Gigabyte's website for viewing their motherboards cpu usage rises to 100% and the browser freezes. Disabling javascript protection and fingerprinting protection for that website fixes the issue.

Pages affected: [[URL/all pages/URLs](https://www.gigabyte.com/Motherboard/B550M-AORUS-ELITE-rev-1x/sp#sp)]
JShelter Version: 0.11.1

OS: Archlinux
Browser: Firefox flatpak 105.0.2
Other extensions that might affect JShelter behaviour: Ublock Origin, Privacy Badger, Decentraleyes

**Comment by polcak** [comment]
I guess that you mean https://www.gigabyte.com/

**Comment by moshiur-raj** [comment]
I don't know if all of gigabyte's website is affected.

**Comment by polcak** [comment]
Please, can you provide URL? I cannot try to reproduce until I know what page is affected.

**Comment by moshiur-raj** [comment]
https://www.gigabyte.com/Motherboard/B550M-AORUS-ELITE-rev-10-11-12#kf

This page is extremely laggy with jshelter installed.

**Comment by polcak** [comment]
We will keep track on the issue at https://pagure.io/JShelter/webextension/issue/111. I will close here. Feel free to provide more details here or on Pagure.
