### ISSUE TITLE
Will JShelter continue to receive updates?

### ISSUE THREAD

**Issue by sillyjaybird** [polcak/jsrestrictor#194]
Will JShelter continue to updated and improved or is v. 0.11.1 the last release?

**Comment by TechnologyClassroom** [comment]
JShelter is still in development. We recently secured additional funds to continue development. There is a live talk going right now at libreplanet.org/2023 if you want to hear about the project.

**Comment by polcak** [comment]
Additionally, we have a mailing list https://lists.nongnu.org/archive/html/js-shield/ and development branches in the current pagure repository https://pagure.io/JShelter/webextension. A new version is likely soon.

As this is not an issue, I am closing as invalid.

**Comment by dumblob** [comment]
I wonder which repository is the primary one - this GitHub one or the Pagure one?

If I wanted to make a PR, which shall I use? I see there are quite some differences in commits in both repos. But both repos seems active. So, how is it actually?

**Comment by polcak** [comment]
We use Pagure for development.

There was a dependabot commit missing in Pagure. Generally, I push to GitHub with a release. But I synced the repos now.

We accept PR both in Pagure and Github.

**Comment by dumblob** [comment]
Thnks for clarification. Could this "duality" be explicitly mentioned at the top of the "Contributing" section in readme?

**Comment by polcak** [comment]
I copied that idea to a related issue of reporting bugs https://pagure.io/JShelter/webextension/issue/92#comment-852146
