### ISSUE TITLE
Strange error on every page I visit

### ISSUE THREAD

**Issue by privacyguy123** [polcak/jsrestrictor#206]
![image](https://github.com/polcak/jsrestrictor/assets/50337995/e1d42f6b-3c52-4b38-8c4f-6385b2e25301)

Is this by design due to some setting I have turned on or? It points to JShelter addon using that ```moz-extension://``` link.

**Comment by polcak** [comment]
Dear @privacyguy123,

Thank you for reporting the issue. I checked 0.15.2 from stores and I was not able to reproduce the error. Please fill in the information below.

## Setup

Pages affected: [URL/all pages/URLs]
JShelter Version: 

Popup information (open JShelter popup on affected pages:

1. Navigate to a page that you are having trouble with: [URL]
2. Click on the JShelter badge icon.
3. Is JavaScript Shield active? [ON/OFF]
3. Is Network Boundary Shield active? [ON/OFF]
3. Is Fingerprint Detector active? [ON/OFF]
4. What fingerprint likelihood does Fingerprint Detector report?
5. Did Fingerprint Detector produce any notifications, if so, what was the notification?
6. Click on the `Modify` button next to the JavaScript Shield label.
7. What is the highlighted level button text?

OS: 
Browser: 
Other extensions that might affect JShelter behaviour: 


## Reproducibility

1. Have you tried another profile/browser/machine/OS? Have you tried replicating your configuration there? Did you trigger the same bug? What exact steps lead to the bug?


2. Have you tried going to options (Global settings) -> Expert settings, backup your configuration (copy the text to a text file), select Reset the configuration? Did it help? If yes, did you try to recover the old configuration from the backup? Did the error appear again?

## Have you tried other steps to solve the issue?

1. I tried X but ...
2. I tried Y but ...
3. I tried Z but ...

[Was there any progress?]

## Additional information / notes

[Other additional notes]

**Comment by privacyguy123** [comment]
Sorry, seperate addon conflict. Please close.
