### ISSUE TITLE
UAS spoofing overhaul (originally Mobile User Agent for mobile browsers)

### ISSUE THREAD

**Issue by thewan056** [polcak/jsrestrictor#22]
Would like to see mobile user agents added to the spoof user agent feature. I tried your extension in
chrome based Yandex for Android and also Kiwi browser for android, both of which has extension support, and they all show desktop pages for sites that think I'm a desktop.

**Comment by polcak** [comment]
I moved the UAS spoofing feature to experimental (efficient from the next release). It seems that it breaks pages and it needs a lot of improvements.

* mobile browser handling
* new releases
* detection of pages that are broken by the fake UAS, e.g. docs.google.com and drive.google.com

Right now, this feature is at low priority but we might return to this in the future.

**Comment by polcak** [comment]
Removed in c9a9b8b5a225cb5dc40f4156b0c0c84698bbeb5c
