### ISSUE TITLE
Worker DedicatedWorkerGlobalScope bypass restrictions (canvas, language, hardwareConcurrency, etc)

### ISSUE THREAD

**Issue by raszpl** [polcak/jsrestrictor#56]
`new Worker(URL.createObjectURL(new Blob(["c = new OffscreenCanvas(100, 1); d = c.getContext('2d'); console.log(d.getImageData)"], {type: 'application/javascript'})))`

returns ƒ getImageData() { [native code] }

`new Worker(URL.createObjectURL(new Blob(["console.log('hardwareConcurrency: ', self.navigator.hardwareConcurrency);"], {type: 'application/javascript'})))`

returns real value, etc.

Probably same deal with ServiceWorker and SharedWorker. I briefly looked into ways of overriding it and so far only way I could come up with is stubbing at the point of worker creation (injecting own script before user one)

ps: OffscreenCanvas/OffscreenCanvasRenderingContext2D also look like something worth patching in window context.

**Comment by polcak** [comment]
Thank you. Just to clarify, this is about the master branch, i.e. currently published version of the extension?

The planned 0.3 version allows to wrap workers and also returns the original toString. Even so, it is worth trying the behaviour of the future 0.3.

**Comment by polcak** [comment]
This will be fixed in imminent 0.5 using the code by G. Maone
