### ISSUE TITLE
Fix wrappings of PH to use parent_object and parent_object_property correctly

### ISSUE THREAD

**Issue by polcak** [polcak/jsrestrictor#57]
E.g. "window.PerformanceEntry" actually modifies "PerformanceEntry.startTime" and "PerformanceEntry.duration"

- [x] Create wiki docs explaining the reasoning behind wrapping objects and explain the properties
- [x] Do not use original_functions in S-HRT
- [ ] Fix the code
- [ ] Make sure that wiki is still up-to-date

Current implementation introduce inconsistencies, does not go through code builders dealing with FF bug 1267027 (#25) and accesses original_functions that will make future modifications of this function harder.

**Comment by polcak** [comment]
See wiki https://github.com/polcak/jsrestrictor/wiki/How-to-write-a-new-wrapper%3F

**Comment by polcak** [comment]
fc25314 removes the wrapping of window.PerformanceEntry as S-PT2 already provides fake PerformanceEntries.

I am waiting for @PeetHornak but it is possible that this can be closed as is.

**Comment by polcak** [comment]
PerformanceEntry re-introduced as a part of #61 with rewritten code.

**Comment by polcak** [comment]
Although there is no confirmation by @PeetHornak, I think that we can close the issue

**Comment by PeetHornak** [comment]
My apologies, forgot about this one. Yes it can be closed because of the reasons you described.
