### ISSUE TITLE
Magnetometer

### ISSUE THREAD

**Issue by polcak** [polcak/jsrestrictor#59]
* https://www.w3.org/TR/magnetometer/
* http://blog.lukaszolejnik.com/privacy-analysis-of-web-browser-access-to-magnetometer-sensor/

Suggested limitations: frequency and precision capping.

**Comment by polcak** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Magnetometer/Magnetometer: Available in Chrome, Opera
Missing in Ff

**Comment by polcak** [comment]
Added in 0.6

**Comment by ihranicky** [comment]
The Magnetometer wrapper was implemented and added with https://github.com/polcak/jsrestrictor/pull/165
Further improvements were added with ba2e37d60e5c7596a03abc1aaea76a40bf544d78 where the wrapper uses the faked device's position to calculate magnetic field vectors.
Improved class-based implementation in fb4236e7bd589fa94ebb8bb4ec2528f3ce8c43d8.
