### ISSUE TITLE
Level 3: Failed to execute 'getRandomValues' on 'Crypto'

### ISSUE THREAD

**Issue by martinbednar** [polcak/jsrestrictor#69]
When level 3 of JSR 0.3 is set, this javascript error occurs in the developer console on multiple websites:

`Level: SEVERE
Source: javascript
Message: Uncaught TypeError: Failed to execute 'getRandomValues' on 'Crypto': parameter 1 is not of type 'ArrayBufferView'.`

This error usually occurs in Google Chrome, but also on several pages in Mozilla Firefox.

This error can probably cause that the website will not load correctly.

This error was caught for example on websites: twitter.com, instagram.com, windowsupdate.com, linkedin.com, apple.com, wikipedia.org.

This error was found out by system tests add in #68 .

**Comment by martinbednar** [comment]
Failed to load twitter.com in Google Chrome with JSR on level 3. It may be caused by #69 .

Without JSR:
![twitterwithout](https://user-images.githubusercontent.com/15677706/89302112-bd5baa00-d66a-11ea-9009-cdbd171120c3.png)

With JSR level 3:
![twitterwith](https://user-images.githubusercontent.com/15677706/89302160-cba9c600-d66a-11ea-9f77-1f6d4a305f1f.png)

**Comment by martinbednar** [comment]
Failed to load instagram.com in Google Chrome with JSR on level 3. It may be caused by #69 .

Without JSR:
![without_jsr](https://user-images.githubusercontent.com/15677706/89303078-f8121200-d66b-11ea-866e-a9335152f97e.png)

With JSR level 3:
![with_jsr](https://user-images.githubusercontent.com/15677706/89303094-fea08980-d66b-11ea-9575-5f1fc129c6d7.png)

**Comment by polcak** [comment]
Closing, see https://pagure.io/JShelter/webextension/issue/33
