### ISSUE TITLE
Linkedin.com + level 3: Failed to load the website logo

### ISSUE THREAD

**Issue by martinbednar** [polcak/jsrestrictor#70]
Failed to load the website logo on linkedin.com in Google Chrome with JSR on level 3.

Without JSR:
![linkedinwithout](https://user-images.githubusercontent.com/15677706/89302813-9ea9e300-d66b-11ea-8020-a2abbc34a611.png)

With JSR:
![linkedinwith](https://user-images.githubusercontent.com/15677706/89302836-a79ab480-d66b-11ea-9604-bddd81928186.png)

**Comment by polcak** [comment]
Cannot reproduce neither in Edge nor Firefox with JShelter 0.9. If this is the main page, it was probably changed in the mean time.
