### ISSUE TITLE
window.name

### ISSUE THREAD

**Issue by polcak** [polcak/jsrestrictor#72]
Very simple cross-origin tracking method of the same tab:

https://developer.mozilla.org/en-US/docs/Web/API/Window/name

```
window.name = "8pdRoEaQCpsjtC8w07dOy7xwXjXrHDyxxmPWBUxQKrh7xfJ4SYFH8QClp6U9T+Ypa8IEa5AwFw3x"
```

Go to completely different web site and `window.name` stays the same.

See also https://2019.www.torproject.org/projects/torbrowser/design/

**Comment by martinbednar** [comment]
Check interaction between window name and object freeze.

**Comment by polcak** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=444222 and https://html.spec.whatwg.org/#history-traversal

I am testing on FF83 and I have the following HTML on two domains:
```html
<html>
<head>
        <title>window.name bug</title>
</head>

<body>
<script>
        document.write(window.name);
        window.name = "foo";
</script>
</body>
```

Each domain setting a different `foo`. When I go forth and back, the domains can see the string of the other domain.
